baseURL = 'https://hoottopic.netlify.app'
languageCode = 'en-us'
title = 'Hoottopic'
theme = "PaperMod"

paginate = 0
disableKinds = ["taxonomy", "term"]

[params]
  mainSections = []

  [params.homeInfoParams]

  [params.assets]
    customCSS = ["css/extended/extended_styles.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

ignoreLogs = ["warning-goldmark-raw-html"]